name: CI/CD for Dockerized App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my_docker_image_name:latest .
        docker images

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my_docker_image_name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy container
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/my_docker_image_name:latest
        docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/my_docker_image_name:latest
